# filepath: /Users/herirusmanto/Learn/Sibermu/mail-scheduler/docker-compose.yml
services:
  app:
    build: .
    container_name: mail_scheduler_app
    env_file:
      - .env
    environment:
      - FLASK_APP=serve.py
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - APP_SETTINGS=${APP_SETTINGS:-DevelopmentConfig}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - '8080:8080'
    volumes:
      - .:/var/www/mail-scheduler
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  worker:
    build: .
    command: python -m flask rq worker
    env_file:
      - .env
    environment:
      - FLASK_APP=serve.py
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - APP_SETTINGS=${APP_SETTINGS:-DevelopmentConfig}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/var/www/mail-scheduler
    depends_on:
      - app
      - redis
      - postgres

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    env_file:
      - .env
    environment:
      - FLASK_APP=serve.py
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - APP_SETTINGS=${APP_SETTINGS:-DevelopmentConfig}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/var/www/mail-scheduler
    depends_on:
      - app
      - redis
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: mail_scheduler_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mail_scheduler_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
