name: Scheduled Tests

permissions:
  contents: read
  statuses: write

on:
  schedule:
    # Run weekly on Sunday at 1:00 AM UTC
    - cron: '0 1 * * 0'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  full-test-suite:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.8.3"
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Lint with flake8
      run: |
        source .venv/bin/activate
        flake8 app tests --count --show-source --statistics

    - name: Run comprehensive tests
      env:
        FLASK_APP: serve.py
        FLASK_DEBUG: 1
        APP_SETTINGS: TestingConfig
        SECRET_KEY: test-secret-key
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        source .venv/bin/activate
        # Run the full test suite with coverage
        pytest --cov=app --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: scheduled-tests
        name: codecov-scheduled
      continue-on-error: true

    - name: Check for warnings and deprecation
      run: |
        source .venv/bin/activate
        # Run tests and capture all warnings
        python -m pytest -xvs --no-header --no-summary -k "not slow" 2>&1 | grep -i "warning\|deprecated\|deprecation" || echo "No warnings found"
      continue-on-error: true
